spring:
  datasource:
    url: jdbc:h2:mem:ev_booking;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  ev:
    api-key: ${EV_API_KEY:sa2hYuhmi00eGKS6uRtrn1cO8vjrnFC9tEhC0din}
